"""empty message

Revision ID: e86d162cf4c1
Revises: 
Create Date: 2019-07-21 12:26:00.532576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e86d162cf4c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crew',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('persons', sa.String(length=3000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crew')
    # ### end Alembic commands ###
